apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hbro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hbro
    app.kubernetes.io/part-of: tkrw-pr714-0075-0022-app
  name: devfile-sample-hbro
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hbro
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hbro
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0022-tenant/tkrw-pr714-0075-0022-app/devfile-sample-hbro@sha256:4f3de8646b997b54527f54ffdaa59c038e7127ae309c7b29178874cfd99c9556
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
