apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hbro
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0022-tenant/tkrw-pr714-0075-0022-app/devfile-sample-hbro@sha256:4f3de8646b997b54527f54ffdaa59c038e7127ae309c7b29178874cfd99c9556
        name: my-nodejs
        resources: {}
status: {}
